export const createProduct = {
  headers: [
    { label: "NAME*", key: "name" },
    { label: "SLUG*", key: "slug" },
    { label: "CATEGORIES*", key: "categories" },
    { label: "SUB CATEGORIES*", key: "subCategories" },
    { label: "DECOR SERIES*", key: "decorSeries" },
    { label: "DECOR NAME*", key: "decorName" },
    { label: "DECOR NUMBER*", key: "decorNumber" },
    { label: "RAL NUMBER*", key: "ralNumber" },
    { label: "SKU*", key: "sku" },
    { label: "SIZES*", key: "sizes" },
    { label: "DESCRIPTIONS", key: "descriptions" },
    { label: "SHORT DESCRIPTION", key: "shortDescription" },
    { label: "IMAGE*", key: "image" },
    { label: "META TITLE", key: "metaTitle" },
    { label: "META DESCRIPTION", key: "metaDescription" },
    { label: "META KEYWORDS", key: "metaKeywords" },
    { label: "STATUS*", key: "status" },
  ],
  data: [
    {
      name: "Product One",
      slug: "product-one",
      categories: "",
      subCategories: "",
      decorSeries: "",
      decorName: "",
      decorNumber: "",
      ralNumber: "",
      sku: "",
      sizes: "",
      descriptions: "",
      shortDescription: "",
      image: "",
      metaTitle: "",
      metaDescription: "",
      metaKeywords: "",
      status: "",
    },
  ],
};

export const updateProduct = {
  headers: [
    { label: "id", key: "id" },
    { label: "name", key: "name" },
    { label: "slug", key: "slug" },
    { label: "categories", key: "categories" },
    { label: "subCategories", key: "subCategories" },
    { label: "decorSeries", key: "decorSeries" },
    { label: "decorName", key: "decorName" },
    { label: "decorNumber", key: "decorNumber" },
    { label: "ralNumber", key: "ralNumber" },
    { label: "subCategories", key: "subCategories" },
    { label: "sku", key: "sku" },
    { label: "sizes", key: "sizes" },
    { label: "a4Image", key: "a4Image" },
    { label: "fullSheetImage", key: "fullSheetImage" },
    { label: "highResolutionImage", key: "highResolutionImage" },
    { label: "metaTitle", key: "metaTitle" },
    { label: "metaDescription", key: "metaDescription" },
    { label: "metaKeywords", key: "metaKeywords" },
    { label: "status", key: "status" },
  ],
};
