export const createProduct = {
  headers: [
    { label: "name", key: "name" },
    { label: "slug", key: "slug" },
    { label: "categories", key: "categories" },
    { label: "subCategories", key: "subCategories" },
    { label: "decorSeries", key: "decorSeries" },
    { label: "decorName", key: "decorName" },
    { label: "decorNumber", key: "decorNumber" },
    { label: "ralNumber", key: "ralNumber" },
    { label: "sku", key: "sku" },
    { label: "sizes", key: "sizes" },
    { label: "descriptions", key: "descriptions" },
    { label: "shortDescription", key: "shortDescription" },
    { label: "image", key: "image" },
    { label: "metaTitle", key: "metaTitle" },
    { label: "metaDescription", key: "metaDescription" },
    { label: "metaKeywords", key: "metaKeywords" },
    { label: "status", key: "status" },
  ],
  data: [
    {
      name: "Produvt One",
      slug: "product-one",
      categories: "",
      subCategories: "",
      decorSeries: "",
      decorName: "",
      decorNumber: "",
      ralNumber: "",
      sku: "",
      sizes: "",
      descriptions: "",
      shortDescription: "",
      image: "",
      metaTitle: "",
      metaDescription: "",
      metaKeywords: "",
      status: "",
    },
  ],
};

export const updateProduct = {
  headers: [
    { label: "id", key: "id" },
    { label: "name", key: "name" },
    { label: "slug", key: "slug" },
    { label: "categories", key: "categories" },
    { label: "subCategories", key: "subCategories" },
    { label: "decorSeries", key: "decorSeries" },
    { label: "decorName", key: "decorName" },
    { label: "decorNumber", key: "decorNumber" },
    { label: "ralNumber", key: "ralNumber" },
    { label: "subCategories", key: "subCategories" },
    { label: "sku", key: "sku" },
    { label: "sizes", key: "sizes" },
    { label: "a4Image", key: "a4Image" },
    { label: "fullSheetImage", key: "fullSheetImage" },
    { label: "highResolutionImage", key: "highResolutionImage" },
    { label: "metaTitle", key: "metaTitle" },
    { label: "metaDescription", key: "metaDescription" },
    { label: "metaKeywords", key: "metaKeywords" },
    { label: "status", key: "status" },
  ],
};
